(()=>{
const $=id=>document.getElementById(id);let state=null,busy=false;
async function call(action,payload){const r=await fetch('/api/setup'+(action?'/'+action:''),{cache:'no-store',...(payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Setup failed');return d}
function message(value,error=false){$('setup-message').textContent=value;$('setup-message').style.color=error?'#a12632':''}
async function refresh(){try{state=await call('');$('setup-checklist').hidden=!state.setup_required;$('setup-missing').replaceChildren(...(state.missing_setup||[]).map(text=>{const li=document.createElement('li');li.textContent=text;return li}));$('setup-finish').disabled=!!state.missing_setup?.length;window.dispatchEvent(new CustomEvent('initial-setup-state',{detail:state}));$('setup-toc').value||=state.source;$('setup-source-status').textContent=state.creators?`${state.creators} creators imported`:'';window.dispatchEvent(new CustomEvent('setup-state',{detail:state}));$('setup-share-path').value||=state.share?.path||'';$('setup-share-user').value||=state.share?.username||'';$('setup-share-domain').value||=state.share?.domain||'';const labels={phone:'Phone number, including country code',code:'Telegram login code',password:'Telegram two-step verification password'};const prompt=labels[state.login];$('setup-answer-form').hidden=!prompt;$('setup-login').disabled=busy||!!prompt||state.login==='connecting';$('setup-login-status').textContent=state.login==='connected'?'✓ Telegram account connected':state.login==='failed'?'Sign-in failed or timed out. Please try again.':state.login==='connecting'?'Connecting to Telegram…':'';if(prompt){$('setup-answer-label').textContent=prompt;$('setup-answer').type=state.login==='phone'?'tel':'password'}}catch(e){message(e.message,true)}}
$('setup-finish').onclick=async()=>{try{await call('complete',{});location.href='/#artists'}catch(e){$('setup-finish-status').textContent=e.message;refresh()}};
$('setup-login').onclick=async()=>{busy=true;try{await call('login',{});message('Follow the sign-in prompts below.')}catch(e){message(e.message,true)}finally{busy=false;refresh()}};
$('setup-answer-form').onsubmit=async e=>{e.preventDefault();const value=$('setup-answer').value;$('setup-answer').value='';try{await call('answer',{value,challenge:state.challenge})}catch(e){message(e.message,true)}refresh()};
$('setup-source-form').onsubmit=async e=>{e.preventDefault();$('setup-import').disabled=true;message('Reading the Table of Contents…');try{const d=await call('source',{url:$('setup-toc').value});message(`Imported ${d.creators} creators. You can now select artists.`)}catch(e){message(e.message,true)}finally{$('setup-import').disabled=false;refresh()}};
document.addEventListener('DOMContentLoaded',()=>{$('setup-share-form').onsubmit=async e=>{e.preventDefault();const password=$('setup-share-password').value;$('setup-share-password').value='';$('setup-share-connect').disabled=true;message('Connecting to the network share…');try{const d=await call('share',{path:$('setup-share-path').value,username:$('setup-share-user').value,password,domain:$('setup-share-domain').value});message('Connected. Download location saved. Reloading settings…');location.reload()}catch(e){message(e.message,true)}finally{$('setup-share-connect').disabled=false}};});
refresh();setInterval(refresh,2000);
})();
